name: GitHub Actions build
on: 
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'npm'


      - name: build
        shell: bash
        run: |
          npm i && npm run build



      # commiting and pushing changes
      - name: commit and push
        shell: bash
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull
          git add -A
          git commit -m 'Generated Files'
          git push
